import type { Skill } from '@/types';

export const backendSkills: Skill[] = [
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'backend',
    level: 'expert',
    proficiency: 90,
    icon: 'nodejs',
    color: '#339933',
    relatedProjects: ['proj-001', 'proj-002'],
    metrics: { yearsExperience: 5, projectCount: 12, lastUsed: '2024-12-01' },
    order: 1,
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'backend',
    level: 'advanced',
    proficiency: 85,
    icon: 'postgresql',
    color: '#4169E1',
    relatedProjects: ['proj-001'],
    metrics: { yearsExperience: 4, projectCount: 8, lastUsed: '2024-11-20' },
    order: 2,
  },
  {
    id: 'prisma',
    name: 'Prisma',
    category: 'backend',
    level: 'advanced',
    proficiency: 88,
    icon: 'prisma',
    color: '#2D3748',
    relatedProjects: ['proj-001'],
    metrics: { yearsExperience: 2, projectCount: 6, lastUsed: '2024-12-01' },
    order: 3,
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    category: 'backend',
    level: 'intermediate',
    proficiency: 75,
    icon: 'graphql',
    color: '#E10098',
    relatedProjects: ['proj-002'],
    metrics: { yearsExperience: 2, projectCount: 4, lastUsed: '2024-10-15' },
    order: 4,
  },
];
