import type { Skill } from '@/types';

export const frontendSkills: Skill[] = [
  {
    id: 'react',
    name: 'React',
    category: 'frontend',
    level: 'expert',
    proficiency: 95,
    icon: 'react',
    color: '#61DAFB',
    relatedProjects: ['proj-001', 'proj-002'],
    metrics: { yearsExperience: 5, projectCount: 15, lastUsed: '2024-12-01' },
    order: 1,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'frontend',
    level: 'expert',
    proficiency: 92,
    icon: 'typescript',
    color: '#3178C6',
    relatedProjects: ['proj-001', 'proj-002', 'proj-003'],
    metrics: { yearsExperience: 4, projectCount: 20, lastUsed: '2024-12-01' },
    order: 2,
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'frontend',
    level: 'expert',
    proficiency: 90,
    icon: 'nextjs',
    color: '#000000',
    relatedProjects: ['proj-001'],
    metrics: { yearsExperience: 3, projectCount: 8, lastUsed: '2024-12-01' },
    order: 3,
  },
  {
    id: 'threejs',
    name: 'Three.js',
    category: 'frontend',
    level: 'advanced',
    proficiency: 85,
    icon: 'threejs',
    color: '#000000',
    relatedProjects: ['proj-003'],
    metrics: { yearsExperience: 2, projectCount: 5, lastUsed: '2024-11-15' },
    learning: true,
    order: 4,
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    category: 'frontend',
    level: 'expert',
    proficiency: 95,
    icon: 'tailwind',
    color: '#06B6D4',
    relatedProjects: ['proj-001', 'proj-002'],
    metrics: { yearsExperience: 3, projectCount: 12, lastUsed: '2024-12-01' },
    order: 5,
  },
];
